# Generated by Django 2.0.4 on 2018-04-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180416_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='hospitalAddress',
            new_name='hospital_address',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospitalName',
            new_name='hospital_name',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospitalPhone',
            new_name='hospital_phone',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hostpitalNumber',
            new_name='hostpital_number',
        ),
    ]
